import React from "react";
import styled, { keyframes } from "styled-components";

const fadeIn = keyframes`
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
`;

const HomePageContainer = styled.div`
  text-align: center;
  padding: 50px;
  animation: ${fadeIn} 1s ease-in-out;
`;

const Title = styled.h1`
  font-size: 4em;
  margin-bottom: 30px;
  color: #2c3e50; /* A nice dark blue */
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
`;

const Introduction = styled.p`
  font-size: 1.3em;
  line-height: 1.8;
  color: #555;
  margin-bottom: 40px;
  max-width: 800px;
  margin-left: auto;
  margin-right: auto;
`;

const Highlight = styled.span`
  color: #e67e22; /* A vibrant orange */
  font-weight: bold;
`;

function HomePage() {
  return (
    <HomePageContainer>
      <Title>
        Fashion Evolution <Highlight>AI</Highlight>!
      </Title>
      <Introduction>
        Welcome to our exploration of AI-generated fashion. Here, you can
        witness the learning process of a simple AI model as it trains to create
        images of clothing. Navigate through the{" "}
        <Highlight>Epoch History</Highlight> to see how the generated fashion
        evolves over the training stages. Use the{" "}
        <Highlight>Generate Random</Highlight> feature to create new, unique
        fashion items based on what the model has learned. In the{" "}
        <Highlight>Fashion Fusion Lab</Highlight>, you can see a visual
        transition between two different fashion items generated by the AI. This
        is a glimpse into the exciting possibilities of artificial intelligence
        in creative design.
      </Introduction>
    </HomePageContainer>
  );
}

export default HomePage;
